### ISSUE TITLE
Keeping current file as reference does not open on the right side

### ISSUE THREAD

**Issue by lowski** [elia/avian-missing.tmbundle#19]
Hi!
Thanks for this bundle. It's really helpful for very common operation.

I have a small problem with keeping current file as reference on the right side.

I've added settings to output html to the right: `defaults write com.macromates.TextMate.preview htmlOutputPlacement right` but TextMate still opens it inside a new window.

Besides that I'm getting some warnings in the output itself:

```
/Users/lucas/Library/Application Support/TextMate/Bundles/avian-missing.tmbundle/Support/lib/doctohtml.rb:22: warning: ambiguous first argument; put parentheses or even spaces
/Users/lucas/Library/Application Support/TextMate/Bundles/avian-missing.tmbundle/Support/lib/doctohtml.rb:53: warning: ambiguous first argument; put parentheses or even spaces
/Users/lucas/Library/Application Support/TextMate/Bundles/avian-missing.tmbundle/Support/lib/doctohtml.rb:89: warning: ambiguous first argument; put parentheses or even spaces
/Users/lucas/Library/Application Support/TextMate/Bundles/avian-missing.tmbundle/Support/lib/doctohtml.rb:90: warning: ambiguous first argument; put parentheses or even spaces
/Users/lucas/Library/Application Support/TextMate/Bundles/avian-missing.tmbundle/Support/lib/doctohtml.rb:91: warning: ambiguous first argument; put parentheses or even spaces
/Users/lucas/Library/Application Support/TextMate/Bundles/avian-missing.tmbundle/Support/lib/doctohtml.rb:92: warning: ambiguous first argument; put parentheses or even spaces
```

Any idea what can be wrong?

**Comment by elia** [comment]
> Hi!
> Thanks for this bundle. It's really helpful for very common operation.

Glad it's helpful to other people as well! Thanks! 😄 

> I've added settings to output html to the right: defaults write com.macromates.TextMate.preview htmlOutputPlacement right but TextMate still opens it inside a new window.

Not 100% sure, but maybe it has to do with the fact that TM2 recently dropped the "preview" state in favor of "release candidate", have you tried from the normal preferences window (in the Projects section)?



> Besides that I'm getting some warnings in the output itself:
> 
> ```
> /Users/lucas/Library/Application Support/TextMate/Bundles/avian-missing.tmbundle/Support/lib/doctohtml.rb:22: warning: ambiguous first argument; put parentheses or even spaces
> /Users/lucas/Library/Application Support/TextMate/Bundles/avian-missing.tmbundle/Support/lib/doctohtml.rb:53: warning: ambiguous first argument; put parentheses or even spaces
> /Users/lucas/Library/Application Support/TextMate/Bundles/avian-missing.tmbundle/Support/lib/doctohtml.rb:89: warning: ambiguous first argument; put parentheses or even spaces
> /Users/lucas/Library/Application Support/TextMate/Bundles/avian-missing.tmbundle/Support/lib/doctohtml.rb:90: warning: ambiguous first argument; put parentheses or even spaces
> /Users/lucas/Library/Application Support/TextMate/Bundles/avian-missing.tmbundle/Support/lib/doctohtml.rb:91: warning: ambiguous first argument; put parentheses or even spaces
> /Users/lucas/Library/Application Support/TextMate/Bundles/avian-missing.tmbundle/Support/lib/doctohtml.rb:92: warning: ambiguous first argument; put parentheses or even spaces
> ```

Thank should be easy to fix, I'll push a commit in a moment.

**Comment by elia** [comment]
fixed by https://github.com/elia/avian-missing.tmbundle/commit/861278a2724a6d16952986821fb1a8461869a156

**Comment by lcmen** [comment]
@elia thanks working fine - no more warnings :).  

> Not 100% sure, but maybe it has to do with the fact that TM2 recently dropped the "preview" state in favor of "release candidate", have you tried from the normal preferences window (in the Projects section)?

You are right again :). Changing `Show command output` to `Right of text view` in `Projects` settings did the job.
