### ISSUE TITLE
Failure running “Ensure trailing newline on save”.

### ISSUE THREAD

**Issue by readysetawesome** [elia/avian-missing.tmbundle#20]
I am at a loss here... apparently, there is some typo somewhere...I'm assuming it is my typo but where should I be looking?

~/Library/Application Support/TextMate/Ruby/1.8.7/bin/ruby: no such file to load -- ubygems (LoadError)

**Comment by readysetawesome** [comment]
I'm using rvm, I had to change `#!/usr/bin/env ruby18` in the offending command to `#!/usr/bin/env ruby`

**Comment by elia** [comment]
Yes "ubygems" is an old alternative file to load "ruby gems" that was added to make it look nice when loaded with the '-r' option from the command line. Happy you were able to fix it, I'm still using this bundle but with "asdf" instead of "rvm"
